### ISSUE TITLE
Mastercard from wayfair

### ISSUE THREAD

**Issue by MerleHester2019** [Mastercard/client-encryption-java#9]

**Comment by TutteRamson** [comment]
Closing the issue as it has no description. Please create a new one with helpful details such as ones listed below for us to assess/reproduce and fix the issue.

- Description of the issue/enhancement suggestion
- The impact it has on the expected behaviour
- Steps to reproduce the issue
- other details(like log snippets, errors received etc)
- pull request(if you have already addressed the problem in your fork of the codebase)
